[project]
name = "mimage"
version = "0.1.2"
description = "A Mojo library for parsing images"
authors = ["Ferdinand Schenck <fwschenck@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
max = ">=24.4.0dev7,<24.5"

[feature.dev.dependencies]
pillow = ">=10.4.0,<10.5"
pre-commit = ">=3.7.1,<3.8"
