[project]
name = "mimage"
version = "0.1.5"
description = "A Mojo library for parsing images"
authors = ["Ferdinand Schenck <fwschenck@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64"]

[tasks]

[dependencies]
max = ">=25.1,<25.2"

[feature.dev.dependencies]
pillow = ">=10.4.0,<10.5"
pre-commit = ">=3.8.0,<4"

[environments]
default = ["dev"]
dev = ["dev"]
